trainingInput:
  moduleName: trainer.task
  region: europe-west4
  stagingBucket: gs://bbgh-sentiment-judge-bucket
  scaleTier: BASIC-GPU
  runtimeVersion: '2.2'
  pythonVersion: '3.7'
  args:
    data_file: gs://bbgh-sentiment-judge-bucket/Data/Dataset.csv
    embeddings_file: gs://bbgh-sentiment-judge-bucket/Data/nkjp+wiki-forms-all-300-cbow-hs-50.txt
    output_dir: gs://bbgh-sentiment-judge-bucket/Models
